# Generated by Django 5.1.2 on 2024-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROB5:_The_Anik-anik_Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('gc_name', models.CharField(max_length=50)),
                ('favorite_collection', models.CharField(max_length=200)),
                ('favorite_collectible', models.CharField(max_length=200)),
                ('hacipupu_owned', models.CharField(max_length=200)),
                ('zsiga_owned', models.CharField(max_length=200)),
                ('hirono_owned', models.CharField(max_length=200)),
                ('monthly_expense_on_collectibles', models.CharField(max_length=100)),
            ],
        ),
    ]